package me.makeachoice.movies.controller.butler.worker;

import android.util.Log;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import me.makeachoice.movies.controller.butler.MyButler;
import me.makeachoice.movies.model.response.tmdb.MovieModel;

/**************************************************************************************************/

/**
 * DetailWorker - handles The Movie DB Http api request for detailed information about a particular
 * movie. It processes the JSON response generated by the request for consumption and passes the
 * processed data up to the Butler.
 *
 * Variable from MyWorker:
 *      mButler;
 *
 * Methods from MyWorker:
 *      Boolean doInBackground(String... params)
 *      void onProgressUpdate(Integer... values)
 *      Boolean onPostExecute(Boolean result)
 *      void onCancelled()
 *
 * Permissions needed in AndroidManifest file:
 *      <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
 *      <uses-permission android:name="android.permission.INTERNET" />
 */
public class DetailWorker extends MyWorker{

/**************************************************************************************************/
/**
 * Class Variables:
 *      MovieModel mMovie - movie model data received from the API call
 */
/**************************************************************************************************/

    //mMovie - movie model data received from the API call
    private MovieModel mMovie;

/**************************************************************************************************/

/**************************************************************************************************/
/**
 * DetailWorker - constructor
 * @param butler - butler class making the API request
 */
    public DetailWorker(MyButler butler){
        //Butler making the API request
        mButler = butler;
    }

/**************************************************************************************************/

/**************************************************************************************************/
/**
 * Getters:
 *      MovieModel getMovie() - get Movie model data received from the API call
 *
 * Setters:
 *      - None -
 */
/**************************************************************************************************/
/**
 * MovieModel getMovie() - get Movie model data received from the API call
 * @return - movie model data received from the API call
 */
    public MovieModel getMovie(){
        return mMovie;
    }

/**************************************************************************************************/

/**************************************************************************************************/
/**
 * Implemented Abstract Class methods
 *      void onPreExecute() - method from MyWorker inherited from AsyncTask; runs on UI Thread.
 *      Boolean doInBackground(String...) - method from MyWorker inherited from AsyncTask; runs on
 *          a background Thread. Makes an API call to get Movie Detail data
 *      void onProgressUpdate(Integer...) - method from MyWorker inherited from AsyncTask; runs on
 *          UI Thread. Does nothing.
 *      void onPostExecute(Boolean) - method from MyWorker inherited from AsyncTask; runs on UI
 *          Thread. Informs the Butler class that the work has completed.
 *      void onCancelled() - method from MyWorker inherited from AsyncTask; runs on UI Thread.
 *          Called if the Task is canceled; does nothing.
 */
/**************************************************************************************************/
/**
 * void onPreExecute() - does nothing.
 */
    @Override
    protected void onPreExecute(){
        //does nothing
   }

/**
 * Boolean doInBackground(String... params) is called after the instantiated Worker class calls
 * XWorker.execute(String...). doInBackground runs on a background thread but is only meant for
 * short processing work, a couple seconds or so.
 *
 * Communicates with The Movie DB api, receives a JSON response and processes the response for
 * consumption by the Butler
 * @param params - a dynamic array of string variable used to construct the url api call
 * @return - returns boolean value to onPostExecute
 */
    protected Boolean doInBackground(String... params){

        //url used
        String api_call = "";
        int count = params.length;

        //construct api call url
        for(int i = 0; i < count; i++){
            api_call = api_call + params[i];
        }

        //result of url call
        Boolean result;
        try {
            //create url object with string variable
            URL url = new URL(api_call);
            //open http connection
            HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();

            //receive input stream from url
            InputStream stream = new BufferedInputStream(urlConnection.getInputStream());
            //create bufferedReader
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(stream));
            //create a string reader to read buffer
            StringBuilder builder = new StringBuilder();


            //string variable to read each line in the buffer
            String inputString;
            //loop through all lines in buffer
            while ((inputString = bufferedReader.readLine()) != null) {
                //append lines into one string
                builder.append(inputString);
            }

            //process JSON response
            result = processJSON(builder);


            //disconnect url connection
            urlConnection.disconnect();
        }
        catch (IOException e) {
            //IO exception, url call failed
            e.printStackTrace();
            return false;
        }

        return result;
    }

/**
 * void onProgressUpdate(Integer...) - runs on UI thread, can post updates to UI
 * @param values - a dynamic array of integers
 */
    protected void onProgressUpdate(Integer... values){
        //does nothing
    }

    /**
 * void onPostExecute(Boolean) - runs on UI thread, called when doInBackground is completed. Lets
 * the Butler class know that the work has completed.
 * @param result - boolean value on whether the background task completed successfully or not
 */
    protected void onPostExecute(Boolean result){
        //inform Butler class that the work has completed
        mButler.workComplete(result);
    }

/**
 * void onCancelled() - called if the Task is canceled. Does nothing.
 */
    @Override
    protected void onCancelled(){
        //does nothing
    }

/**************************************************************************************************/

/**************************************************************************************************/
/**
 * Class methods
 *      Boolean processJSON(StringBuilder) - process raw JSON data to MovieModel
 */
/**************************************************************************************************/
/**
 * Boolean processJSON(StringBuilder) - process raw JSON data to MovieModel data
 * @param builder - raw JSON data
 * @return - result flag if JSON process was successful or not
 */
    private Boolean processJSON(StringBuilder builder){
        //mMovie = new MovieModel();
        try{
            //convert string to JSON Object
            JSONObject topLevel = new JSONObject(builder.toString());

            //create Gson object
            Gson gson = new GsonBuilder().create();

            //convert JSON data to MovieModel data
            mMovie = gson.fromJson(topLevel.toString(), MovieModel.class);

        }
        catch(JSONException e){
            Log.d("Movies", "***** JSONException - processJSON *****");
            e.printStackTrace();
            return false;
        }
        return true;

    }

/**************************************************************************************************/

}
